### YamlMime:ManagedReference
items:
- uid: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings
  commentId: T:Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings
  id: FlexibleColorPicker.AdvancedSettings
  parent: Packages.FlexibleColorPicker.Scripts
  children:
  - Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.a
  - Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.b
  - Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.g
  - Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.Get(System.Int32)
  - Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.h
  - Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.mainStatic
  - Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.r
  - Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.s
  - Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.v
  langs:
  - csharp
  - vb
  name: FlexibleColorPicker.AdvancedSettings
  nameWithType: FlexibleColorPicker.AdvancedSettings
  fullName: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings
  type: Class
  source:
    id: AdvancedSettings
    path: ''
    startLine: 352
  assemblies:
  - cs.temp.dll
  namespace: Packages.FlexibleColorPicker.Scripts
  syntax:
    content: public class FlexibleColorPicker.AdvancedSettings
    content.vb: Public Class FlexibleColorPicker.AdvancedSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.mainStatic
  commentId: F:Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.mainStatic
  id: mainStatic
  parent: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings
  langs:
  - csharp
  - vb
  name: mainStatic
  nameWithType: FlexibleColorPicker.AdvancedSettings.mainStatic
  fullName: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.mainStatic
  type: Field
  source:
    id: mainStatic
    path: ''
    startLine: 355
  assemblies:
  - cs.temp.dll
  namespace: Packages.FlexibleColorPicker.Scripts
  syntax:
    content: public bool mainStatic
    return:
      type: System.Boolean
    content.vb: Public mainStatic As Boolean
- uid: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.r
  commentId: F:Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.r
  id: r
  parent: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings
  langs:
  - csharp
  - vb
  name: r
  nameWithType: FlexibleColorPicker.AdvancedSettings.r
  fullName: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.r
  type: Field
  source:
    id: r
    path: ''
    startLine: 357
  assemblies:
  - cs.temp.dll
  namespace: Packages.FlexibleColorPicker.Scripts
  syntax:
    content: public FlexibleColorPicker.AdvancedSettings.PSettings r
    return:
      type: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.PSettings
    content.vb: Public r As FlexibleColorPicker.AdvancedSettings.PSettings
- uid: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.g
  commentId: F:Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.g
  id: g
  parent: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings
  langs:
  - csharp
  - vb
  name: g
  nameWithType: FlexibleColorPicker.AdvancedSettings.g
  fullName: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.g
  type: Field
  source:
    id: g
    path: ''
    startLine: 358
  assemblies:
  - cs.temp.dll
  namespace: Packages.FlexibleColorPicker.Scripts
  syntax:
    content: public FlexibleColorPicker.AdvancedSettings.PSettings g
    return:
      type: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.PSettings
    content.vb: Public g As FlexibleColorPicker.AdvancedSettings.PSettings
- uid: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.b
  commentId: F:Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.b
  id: b
  parent: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings
  langs:
  - csharp
  - vb
  name: b
  nameWithType: FlexibleColorPicker.AdvancedSettings.b
  fullName: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.b
  type: Field
  source:
    id: b
    path: ''
    startLine: 359
  assemblies:
  - cs.temp.dll
  namespace: Packages.FlexibleColorPicker.Scripts
  syntax:
    content: public FlexibleColorPicker.AdvancedSettings.PSettings b
    return:
      type: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.PSettings
    content.vb: Public b As FlexibleColorPicker.AdvancedSettings.PSettings
- uid: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.h
  commentId: F:Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.h
  id: h
  parent: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings
  langs:
  - csharp
  - vb
  name: h
  nameWithType: FlexibleColorPicker.AdvancedSettings.h
  fullName: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.h
  type: Field
  source:
    id: h
    path: ''
    startLine: 360
  assemblies:
  - cs.temp.dll
  namespace: Packages.FlexibleColorPicker.Scripts
  syntax:
    content: public FlexibleColorPicker.AdvancedSettings.PSettings h
    return:
      type: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.PSettings
    content.vb: Public h As FlexibleColorPicker.AdvancedSettings.PSettings
- uid: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.s
  commentId: F:Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.s
  id: s
  parent: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings
  langs:
  - csharp
  - vb
  name: s
  nameWithType: FlexibleColorPicker.AdvancedSettings.s
  fullName: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.s
  type: Field
  source:
    id: s
    path: ''
    startLine: 361
  assemblies:
  - cs.temp.dll
  namespace: Packages.FlexibleColorPicker.Scripts
  syntax:
    content: public FlexibleColorPicker.AdvancedSettings.PSettings s
    return:
      type: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.PSettings
    content.vb: Public s As FlexibleColorPicker.AdvancedSettings.PSettings
- uid: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.v
  commentId: F:Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.v
  id: v
  parent: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings
  langs:
  - csharp
  - vb
  name: v
  nameWithType: FlexibleColorPicker.AdvancedSettings.v
  fullName: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.v
  type: Field
  source:
    id: v
    path: ''
    startLine: 362
  assemblies:
  - cs.temp.dll
  namespace: Packages.FlexibleColorPicker.Scripts
  syntax:
    content: public FlexibleColorPicker.AdvancedSettings.PSettings v
    return:
      type: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.PSettings
    content.vb: Public v As FlexibleColorPicker.AdvancedSettings.PSettings
- uid: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.a
  commentId: F:Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.a
  id: a
  parent: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings
  langs:
  - csharp
  - vb
  name: a
  nameWithType: FlexibleColorPicker.AdvancedSettings.a
  fullName: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.a
  type: Field
  source:
    id: a
    path: ''
    startLine: 363
  assemblies:
  - cs.temp.dll
  namespace: Packages.FlexibleColorPicker.Scripts
  syntax:
    content: public FlexibleColorPicker.AdvancedSettings.PSettings a
    return:
      type: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.PSettings
    content.vb: Public a As FlexibleColorPicker.AdvancedSettings.PSettings
- uid: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.Get(System.Int32)
  commentId: M:Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.Get(System.Int32)
  id: Get(System.Int32)
  parent: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings
  langs:
  - csharp
  - vb
  name: Get(int)
  nameWithType: FlexibleColorPicker.AdvancedSettings.Get(int)
  fullName: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.Get(int)
  type: Method
  source:
    id: Get
    path: ''
    startLine: 377
  assemblies:
  - cs.temp.dll
  namespace: Packages.FlexibleColorPicker.Scripts
  summary: "\nGet PSettings for value associated with the given picker index.\nReturns default PSettings if none exists.\n"
  example: []
  syntax:
    content: public FlexibleColorPicker.AdvancedSettings.PSettings Get(int i)
    parameters:
    - id: i
      type: System.Int32
    return:
      type: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.PSettings
    content.vb: Public Function [Get](i As Integer) As FlexibleColorPicker.AdvancedSettings.PSettings
  overload: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.Get*
  nameWithType.vb: FlexibleColorPicker.AdvancedSettings.Get(Integer)
  fullName.vb: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.Get(Integer)
  name.vb: Get(Integer)
references:
- uid: Packages.FlexibleColorPicker.Scripts
  commentId: N:Packages.FlexibleColorPicker.Scripts
  name: Packages.FlexibleColorPicker.Scripts
  nameWithType: Packages.FlexibleColorPicker.Scripts
  fullName: Packages.FlexibleColorPicker.Scripts
  spec.csharp:
  - uid: Packages
    name: Packages
  - name: .
  - uid: Packages.FlexibleColorPicker
    name: FlexibleColorPicker
  - name: .
  - uid: Packages.FlexibleColorPicker.Scripts
    name: Scripts
  spec.vb:
  - uid: Packages
    name: Packages
  - name: .
  - uid: Packages.FlexibleColorPicker
    name: FlexibleColorPicker
  - name: .
  - uid: Packages.FlexibleColorPicker.Scripts
    name: Scripts
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.PSettings
  commentId: T:Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.PSettings
  parent: Packages.FlexibleColorPicker.Scripts
  name: FlexibleColorPicker.AdvancedSettings.PSettings
  nameWithType: FlexibleColorPicker.AdvancedSettings.PSettings
  fullName: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.PSettings
  spec.csharp:
  - uid: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker
    name: FlexibleColorPicker
  - name: .
  - uid: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings
    name: AdvancedSettings
  - name: .
  - uid: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.PSettings
    name: PSettings
  spec.vb:
  - uid: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker
    name: FlexibleColorPicker
  - name: .
  - uid: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings
    name: AdvancedSettings
  - name: .
  - uid: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.PSettings
    name: PSettings
- uid: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.Get*
  commentId: Overload:Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.Get
  name: Get
  nameWithType: FlexibleColorPicker.AdvancedSettings.Get
  fullName: Packages.FlexibleColorPicker.Scripts.FlexibleColorPicker.AdvancedSettings.Get
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
